"""Core data types for the engine pipeline."""

from __future__ import annotations

from dataclasses import dataclass, field
from decimal import Decimal
from typing import Literal, Protocol, runtime_checkable

import pandas as pd

# ---------------------------------------------------------------------------
# Value types
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class Order:
    """A trade order generated by a Rule.

    Order is an immutable request object. Rules generate Orders;
    the OrderRouter (e.g. SimBroker) receives and processes them.
    Order lifecycle state (open -> filled/canceled/expired) is
    tracked by the OrderBook, not on the Order itself.

    Attributes
    ----------
    symbol : str
        The ticker symbol to trade.
    side : Literal["BUY", "SELL"]
        Trade direction.
    shares : int
        Number of shares to trade.
    order_type : Literal["market", "limit", "stop", "stop_limit", "trailing_stop"]
        Order type. Default is "market".

        - ``"market"``: execute at current market price
        - ``"limit"``: execute at limit_price or better
        - ``"stop"``: trigger a market order when price hits stop_price
        - ``"stop_limit"``: trigger a limit order when price hits stop_price
        - ``"trailing_stop"``: stop price trails the market by trail_pct
    limit_price : Decimal or None
        Limit price for limit and stop_limit orders.
    stop_price : Decimal or None
        Stop trigger price for stop and stop_limit orders.
    trail_pct : float or None
        Trailing percentage for trailing_stop orders.
        E.g. 0.05 means the stop trails 5% below the high-water mark.
    """

    symbol: str
    side: Literal["BUY", "SELL"]
    shares: int
    order_type: Literal[
        "market", "limit", "stop", "stop_limit", "trailing_stop"
    ] = "market"
    limit_price: Decimal | None = None
    stop_price: Decimal | None = None
    trail_pct: float | None = None


@dataclass(frozen=True)
class Fill:
    """A completed execution of an Order.

    Attributes
    ----------
    order : Order
        The original order that was filled.
    filled_price : Decimal
        Actual execution price (after slippage adjustment).
    filled_at : str
        ISO date string of fill time.
    fee : Decimal
        Transaction fee charged for this fill. Default is 0.
    """

    order: Order
    filled_price: Decimal
    filled_at: str
    fee: Decimal = Decimal("0")


@dataclass(frozen=True)
class Position:
    """A single holding in a portfolio.

    Attributes
    ----------
    symbol : str
        The ticker symbol.
    shares : int
        Number of shares held.
    avg_cost : Decimal
        Volume-weighted average cost per share.
    """

    symbol: str
    shares: int
    avg_cost: Decimal


@dataclass
class Portfolio:
    """Mutable portfolio state tracking cash and positions.

    Attributes
    ----------
    cash : Decimal
        Available cash balance.
    positions : dict[str, Position]
        Current holdings keyed by symbol.
    """

    cash: Decimal
    positions: dict[str, Position] = field(default_factory=dict)
    bar_prices: dict[str, Decimal] = field(default_factory=dict)

    def total_value(self, prices: dict[str, Decimal]) -> Decimal:
        """Calculate total portfolio value (cash + positions)."""
        pos_value = sum(
            (pos.shares * prices.get(pos.symbol, Decimal("0"))
             for pos in self.positions.values()),
            Decimal("0"),
        )
        return self.cash + pos_value


# ---------------------------------------------------------------------------
# Execution protocols (Section 4.6 — three-protocol architecture)
# ---------------------------------------------------------------------------

@runtime_checkable
class OrderRouter(Protocol):
    """Order interface: the only exit point for strategy to submit orders."""

    def submit_order(self, order: Order) -> str: ...


@runtime_checkable
class FillReceiver(Protocol):
    """Fill interface: the only entry point for fills to reach the portfolio."""

    def get_fills(self) -> list[Fill]: ...


# ---------------------------------------------------------------------------
# Component protocols (Section 5.3-5.5)
# ---------------------------------------------------------------------------

@runtime_checkable
class Indicator(Protocol):
    """Indicator contract: pure function, per-symbol vectorized computation."""

    name: str

    def compute(self, mktdata: pd.DataFrame, **params: object) -> pd.Series: ...


@runtime_checkable
class Signal(Protocol):
    """Signal contract: cross-sectional vectorized computation."""

    name: str

    def compute(
        self, mktdata: dict[str, pd.DataFrame], **params: object
    ) -> dict[str, pd.Series]: ...


@runtime_checkable
class Rule(Protocol):
    """Rule contract: bar-by-bar stateful evaluation."""

    name: str

    def evaluate(
        self, symbol: str, row: pd.Series, portfolio: Portfolio
    ) -> Order | None: ...
